/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assignmentlab3;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.User;
import model.UserDirectory;

/**
 *
 * @author Pc
 */
public class createPanel extends javax.swing.JPanel {

    /**
     * Creates new form createPanel
     */
    JPanel bottomPanel; 
    UserDirectory users;
    public createPanel(JPanel bottomPanel,UserDirectory users) {
        initComponents();
        this.bottomPanel=bottomPanel;
        this.users=users;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        contactinfoLable = new javax.swing.JLabel();
        employeeidlabel = new javax.swing.JLabel();
        agelabel = new javax.swing.JLabel();
        startdateLabel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        emailLable = new javax.swing.JLabel();
        CellphonLabel = new javax.swing.JLabel();
        PhotoLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        employeeidField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        startdateField = new javax.swing.JTextField();
        levelField = new javax.swing.JTextField();
        cellphoneField = new javax.swing.JTextField();
        photoField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        genderLabel = new javax.swing.JLabel();
        genderField = new javax.swing.JTextField();
        uploadLabel = new javax.swing.JButton();

        nameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nameLabel.setText("NAME:");

        titleLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("EMPLOYEE'S PROFILE");

        contactinfoLable.setBackground(new java.awt.Color(51, 51, 0));
        contactinfoLable.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        contactinfoLable.setForeground(new java.awt.Color(0, 51, 51));
        contactinfoLable.setText("CONTACT Info.");

        employeeidlabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        employeeidlabel.setText("EMPLOYEE ID:");

        agelabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        agelabel.setText("AGE:");

        startdateLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        startdateLabel.setText("START DATE:");

        levelLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        levelLabel.setText("LEVEL:");

        emailLable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        emailLable.setText("EMAIL:");

        CellphonLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CellphonLabel.setText("CELLPHINE NUMBER:");

        PhotoLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        PhotoLabel.setText("PHOTO:");

        employeeidField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeidFieldActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        genderLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        genderLabel.setText("GENDER:");

        uploadLabel.setText("Upload");
        uploadLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactinfoLable)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailLable, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CellphonLabel)))
                            .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(levelField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(photoField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeidField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startdateField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cellphoneField)
                            .addComponent(emailField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(uploadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(389, 389, 389))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeidField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agelabel)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startdateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(startdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelLabel)
                    .addComponent(levelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(genderLabel)
                        .addGap(40, 40, 40)
                        .addComponent(contactinfoLable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CellphonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cellphoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLable, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(photoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uploadLabel)))
                    .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void employeeidFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeidFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeidFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        
        User newUser =new User();
        try{
        newUser.setName(nameField.getText());
        newUser.setEmployeeID(Integer.parseInt(employeeidField.getText()));
        newUser.setAge(Integer.parseInt(ageField.getText()));
        newUser.setGender(genderField.getText());
        newUser.setStartdate(Long.parseLong(startdateField.getText()));
        newUser.setLevel(levelField.getText());
        newUser.setCellphonenumber(Long.parseLong(cellphoneField.getText()));
        newUser.setEmail(emailField.getText());
        newUser.setPhoto(photoField.getText());
            }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Please insert correct information", "Error", HEIGHT);
                    }
        users.adduser(newUser);
        //System.out.println(users);
        JOptionPane.showMessageDialog(this, "Employee Information Save Successfully", "success", HEIGHT);

            

        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void uploadLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uploadLabelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CellphonLabel;
    private javax.swing.JLabel PhotoLabel;
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel agelabel;
    private javax.swing.JTextField cellphoneField;
    private javax.swing.JLabel contactinfoLable;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLable;
    private javax.swing.JTextField employeeidField;
    private javax.swing.JLabel employeeidlabel;
    private javax.swing.JTextField genderField;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField levelField;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField photoField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField startdateField;
    private javax.swing.JLabel startdateLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton uploadLabel;
    // End of variables declaration//GEN-END:variables
}
